version: '3.8'
services:
  agent-api:
    build: .
    ports:
    # <the port on the host machine you want to map to the docker container, like your VM you deploy to>:<the port you run your api on in the docker container, check your dockerfile for this>
      - "8000:8000"
  xmtp-service:
    build: ./xmtp-service
    working_dir: /app
    env_file:
      - ./.env
    # /Users/kevinjoo/Downloads/0xEffB8d668e31CD8F598fbF8447b2Aa12BfAAEd20_XMTPbundle.txt